### ISSUE TITLE
Import to address not working.

### ISSUE THREAD

**Issue by Busti** [SRAhub/MinimaxSimulator#18]
Specifying a starting address when importing a binary file does not work.  
The data ends up at address 0 regardless.

**Comment by prohde** [comment]
That's a Java thing. If you use the arrow buttons on the right side or if you press enter after entering a number it works. The component updates its value after end of input. Unfortunately end of input is not fired after pressing a numeric key on the keyboard. Changing the value with the arrow buttons on the right side fires the event es well as pressing enter.
I am sorry for any inconveniences but I did not find a way to fix this behavior.

**Comment by Busti** [comment]
Thank you, that works for us.  
Maybe a button to manually fire the event would be more intuitive?

**Comment by prohde** [comment]
Closed by PR #24
