### ISSUE TITLE
Signaltable import error

### ISSUE THREAD

**Issue by Exopandora** [SRAhub/MinimaxSimulator#21]
If you save a project with an empty signaltable and then try to import it again you will be left with an error message.
The problem is that `row` is a JSONObject when the exporter writes it to a file. Thus saving `row` as `row {}` and not as `row []`.
The importer then assumes that `row` is a JSONArray throwing an error message when `row` is `row {}`.

**Comment by prohde** [comment]
I will fix this. Nevertheless I do not think saving a project with an empty signal table will happen very often.

**Comment by prohde** [comment]
If you save a project with an empty signaltable there is no row entry in the JSON file. This leads to the error message. If you add `row[]` to the JSON file than the importer loads the empty signaltable. But this leads to an IllegalStateException in MinimaxSimulation.
The only suitable solution I can offer you is to add an empty row to the table if there is no row imported from the loaded project.

**Comment by prohde** [comment]
Closed by PR #23!
