### ISSUE TITLE
Debug-Simulation uses old memory

### ISSUE THREAD

**Issue by Exopandora** [SRAhub/MinimaxSimulator#25]
Steps to reproduce:
1. Import a memory file
2. Start a simulation
3. Import another memory file
4. Stop and refresh the simulation
5. Start a new simulation
Result: The new simulation will use the old memory

I guess pressing the stop button overwrites the new memory with the old one resulting into unwanted behavior

**Comment by prohde** [comment]
You are not supposed to change anything during a running simulation. But maybe I will implement a check and warning dialog.
