### ISSUE TITLE
Debug memory table bug

### ISSUE THREAD

**Issue by Exopandora** [SRAhub/MinimaxSimulator#26]
When the simulation writres to the memory at the relative row (ROW mod 16) it will show the new value although its not the right address. For example: Writing a 0 to address 32 would show you a 0 at address 16 if your current view is 0 - 16. If you update the table by scrolling down and back up again it will be gone.
Is this intentional ?

**Comment by prohde** [comment]
This behavior is not intentional. I consider this as a minor bug and will fix this in some time.
