### ISSUE TITLE
Import Data from File to Memory

### ISSUE THREAD

**Issue by Nexu18** [SRAhub/MinimaxSimulator#29]
When importing data from a file to the machines memory, if one of the last three bytes of an integer begins with 1 in binary representation, the integer value will be wrong (0xFFFFB000 instead of 0x0000B000 for instance). 
This does not happen in the benchmarks, as they don't have a single byte that starts with 1 in binary representation (as far as I'm aware), but it does render other files that I have constructed for the machine useless.

**Comment by prohde** [comment]
I will try to figure out why this happens.
