### ISSUE TITLE
MAR overflow exception

### ISSUE THREAD

**Issue by JoFalken** [SRAhub/MinimaxSimulator#35]
When trying to write 4 bytes in MAR (which is limited to 3 bytes) instead of truncating the simulator extends MAR to 4 bytes (seen in debug mode). Using MAR in another operation afterward results in an overflow exception.
For example:
MAR <- 0xff000000;
MDR <- 8;
M[MAR] <- MDR;

**Comment by prohde** [comment]
@OpusV 
What do we want to do? I think there are two possibilities.
1. truncate the first byte but that could result in unwanted behaviour of the own program to simulate
1. raise an exception so the user is aware of the problem and is able to fix his/her program

**Comment by prohde** [comment]
According to the lecture the machine should truncate the first byte.
