### ISSUE TITLE
wrong background color of schematics using JPG export

### ISSUE THREAD

**Issue by prohde** [SRAhub/MinimaxSimulator#7]
The background color of the exported schematics is supposed to be white. But exporting the machine schematics as JPG leads to a strange background color.

| expected output (like PNG export) | actual output of JPG export |
|     :---:      |     :---:      |
| ![schematics](https://cloud.githubusercontent.com/assets/9991232/12696918/78e98c28-c776-11e5-8458-76953b80768d.png) | ![schematics](https://cloud.githubusercontent.com/assets/9991232/12696917/788419ce-c776-11e5-8f4b-82cca8654622.jpg) |

**Comment by wlfbck** [comment]
Just a guess: Maybe something with alpha channel/transparency?

**Comment by prohde** [comment]
Indeed! This was my first guess, too. The issue was meant as a reminder. Well, it is fixed now.
